name: My first workflow
on: push 

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Docker
    steps:
    - name: checkoutrepo
      uses: actions/checkout@v4
    - name: DockerHub login
      uses: docker/login-action@v2.2.0
      with: 
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}